### ISSUE TITLE
NAME table is not supported？

### ISSUE THREAD

**Issue by db300** [watertrans/GlyphLoader#2]

**Comment by watertrans** [comment]
@db300 thanks for the issue. Indeed it's not supported yet.
I will implement an API similar to WPF's GlyphTypeface.

**Comment by db300** [comment]
@watertrans ok, I see. I'll fork and try to parse the NameTable.

**Comment by watertrans** [comment]
I've released 1.2, it supports.

**Comment by db300** [comment]
Great.
